name = "access"
main = "index.js"
compatibility_date = "2025-06-04"
workers_dev = true

[vars]
# IP to config name mapping (this is now the sole source for IP addresses and their config names)
IP_CONFIG_MAP = '{"31.56.206.129:444": "ğŸ¥Kiwiâ€”ğŸ‡«ğŸ‡®Fin/TEST"}'